backend:
  name: git-gateway
  branch: main
search: true
local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

media_folder: "public/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" , required: false }
      - { label: "Description", name: "description", widget: "string" , required: false }
      - { label: "Date", name: "date", widget: "datetime" , required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] , required: false }
      - { label: "Featured Image", name: "image", widget: "image" , required: false }
      - { label: "Image Caption", name: "imageAlt", widget: "string" , required: false }
      - { label: "Body", name: "body", widget: "markdown" , required: false }

  - name: "faq"
    label: "FAQ"
    folder: "src/content/faq"
    create: true
    slug: "{{slug}}"
    fields:
        - { label: "Title", name: "title", widget: "string" , required: false }
        - { label: "Description", name: "description", widget: "string" , required: false }
        - { label: "Tags", name: "tags", widget: "list", default: ["faq"] , required: false }
        - { label: "Body", name: "body", widget: "markdown" , required: false }